export const coreValueEmojis: Record<string, string> = {
  Atheist: "⚛️",
  Christian: "✝️",
  Catholic: "✝️",
  Buddhist: "☸️",
  Hindu: "🕉️",
  Jewish: "✡️",
  Muslim: "☪️",
  "Spiritual but not religious": "✨",
  Agnostic: "🤔",
  Other: "💫",
  "Long-term": "💍",
  "Short-term": "🔥",
  Casual: "😈",
  "Open to Anything": "🤔",
};
